spring.application.name=TellTale
# Connexion à la base de données (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/telltale
spring.datasource.username=captain
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate (Le moteur qui fait le lien Objet <-> SQL)
# "update" = Crée ou met à jour les tables automatiquement au démarrage
spring.jpa.hibernate.ddl-auto=update

# Affiche les requêtes SQL dans la console (super utile pour apprendre)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
